name: MyFitnessPal Export

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  run-export:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./myfitnesspal-export
      run: |
        pip install pipenv
        pipenv install

    - name: Run MyFitnessPal export script
      working-directory: ./myfitnesspal-export
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        IMAP_URL: ${{ secrets.IMAP_URL }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
        pipenv run python main.py