name: Export Streams Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Run at midnight EST (5:00 UTC)

jobs:
  export_streams:
    runs-on: ubuntu-latest
    steps:
    - name: Check out scripts repository
      uses: actions/checkout@v4
      with:
        repository: RamVasuthevan/scripts
        path: scripts
        token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with repo scope

    - name: Check out dogsheep-data repository
      uses: actions/checkout@v4
      with:
        repository: RamVasuthevan/dogsheep-data
        path: dogsheep-data
        ref: test-streams-export
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pipenv
        cd scripts
        pipenv install

    - name: Run export script
      run: |
        cd scripts
        pipenv run python streams-export/export_streams.py ${{ secrets.STREAMS_USERNAME }} ../temp_output
      env:
        PYTHONUNBUFFERED: 1

    - name: Move exported data
      run: |
        mkdir -p dogsheep-data/streams
        cp -R temp_output/* dogsheep-data/streams/

    - name: Commit and push if changed
      run: |
        cd dogsheep-data
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update streams data" && git push origin test-streams-export)